### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by elhakimz** [dovecot/imaptest#16]
make install
Making install in src
  CC       imaptest-checkpoint.o
checkpoint.c:3:10: fatal error: 'lib.h' file not found
#include "lib.h"
         ^~~~~~~
1 error generated.
make[1]: *** [imaptest-checkpoint.o] Error 1
make: *** [install-recursive] Error 1

**Comment by cmouse** [comment]
You need dovecot-dev or dovecot-devel installed first.

**Comment by cmouse** [comment]
or need dovecot installed from sources

**Comment by slusarz** [comment]
Closing due to no feedback.
