### ISSUE TITLE
Current NOTIFY tests are invalid

### ISSUE THREAD

**Issue by ksmurchison** [dovecot/imaptest#18]
The current NOTIFY tests (src/tests/notify) use the MessageNew, MessageExpunge, and FlagChange events independently, which is invalid per RFC 5465, Section 5:

```
   If the FlagChange and/or AnnotationChange events are specified,
   MessageNew and MessageExpunge MUST also be specified by the client.
   Otherwise, the server MUST respond with the tagged BAD response.

   If one of MessageNew or MessageExpunge is specified, then both events
   MUST be specified.  Otherwise, the server MUST respond with the
   tagged BAD response.

```

**Comment by sirainen** [comment]
Somehow I had thought it applied only to selected mailbox, but looks like not. I'll get that fixed.

**Comment by ksmurchison** [comment]
I initially though they same thing until I read the notes in the ABNF, and then went back and read the prose.

**Comment by sirainen** [comment]
Fixed
