### ISSUE TITLE
Bad ESEARCH test mails

### ISSUE THREAD

**Issue by shikharid** [dovecot/imaptest#35]
https://github.com/dovecot/imaptest/blob/main/src/tests/esearch.mbox

These emails have no headers, not even a date header.

Any particular reason?

[RFC 5322 clearly states that](https://datatracker.ietf.org/doc/html/rfc5322#section-3.6):

> The only required header fields are the origination date field and
>    the originator address field(s).  All other header fields are
>    syntactically optional.

So these emails should atleast have date and from headers

It's a small fix, I already have a fork with these use proper emails similar to other tests.
Let me know and I will raise a PR

**Comment by sirainen** [comment]
Pull request would be helpful, thanks. I just did it this way because Dovecot doesn't care about missing headers and they weren't relevant for the test.

**Comment by shikharid** [comment]
Thanks for the quick reply!
Here you go: https://github.com/dovecot/imaptest/pull/36

**Comment by shikharid** [comment]
Hey @sirainen, these changes are still not available in main

**Comment by sirainen** [comment]
Oh, the git repo syncing has broken again because of some changes merged directly to github. I think need to wait for @cmouse to fix it after he comes back from vacation.

**Comment by cmouse** [comment]
Merged as b96f818d9b62ad016d79dae999ff69544e797ca3
