### ISSUE TITLE
Error compiling imaptest 20181206

### ISSUE THREAD

**Issue by moseleymark** [dovecot/imaptest#6]
Tried a few different versions of dovecot src. I'd do a MR but I don't know if this is the right solution for everyone.
I was getting the following error trying to compile (trimmed down):
imaptest-commands.o: In function `command_send_binary':
/build/dovecot/imaptest-20181206/src/commands.c:152: undefined reference to `t_pop_check'
collect2: error: ld returned 1 exit status
Makefile:549: recipe for target 'imaptest' failed

I added to src/commands.c the following include:
#include "data-stack.h"

and it compiled just fine.

**Comment by cmouse** [comment]
Which version of dovecot are you compiling imaptest against?

**Comment by moseleymark** [comment]
I tried against 2.2.36 and 2.2.32, as well as dovecot-20190405. I was going to do a git checkout but before doing that, I added that include and made the compile happy.

**Comment by cmouse** [comment]
Please use `core-2.2` branch with 2.2.x

**Comment by moseleymark** [comment]
With core-2.2 checkout out, it compiles cleanly against dovecot-2.2.36 without any modificatons.
